title: Tigerfoods
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Comida de verdad para tu mascota; desde Bogotá con mucho cariño.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-feed
  - jekyll-postcss

exclude:
  - purgecss.config.js
  - tags
  - tags.lock
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - .bundle
  # - yarn.lock

