title: Tigerfoods
email: your-email@example.com
description: >- 
  Comida de verdad para tu mascota; desde Bogotá con mucho cariño.
baseurl: "" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
logopath: "./assets/img/logo.png"
url: "https://tiger-foods.pet" 
plugins:
  - jekyll-feed
  - jekyll-postcss

exclude:
  - purgecss.config.js
  - tags
  - tags.lock
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - .bundle

